---
apiVersion: v1
kind: Pod
metadata:
  name: vault-agent-example
spec:
  
  serviceAccountName: vault-auth
  
  restartPolicy: Never

  volumes:
  - name: vault-token
    emptyDir:
      medium: Memory
  
  - name: config
    configMap:
      name: example-vault-agent-config
      items:
      - key: vault-agent-config.hcl
        path: vault-agent-config.hcl

      - key: consul-template-config.hcl
        path: consul-template-config.hcl
  
  - name: shared-data
    emptyDir: {}

  containers:
  - name: vault-agent-auth
    image: vault

    volumeMounts:
    - name: vault-token
      mountPath: /home/vault
    
    - name: config
      mountPath: /etc/vault
    
    # This assumes Vault running on local host and K8s running in Minikube using VirtualBox
    env:
    - name: VAULT_ADDR
      value: http://10.0.2.2:8200
    
    command: ["/bin/sh"]
    args:
    - "-c"
    - |
      cat /etc/vault/vault-agent-config.hcl

      vault agent -config=/etc/vault/vault-agent-config.hcl

      cat /home/vault/.vault-token
  
  - name: consul-template
    image: hashicorp/consul-template
    imagePullPolicy: Always

    volumeMounts:
    - name: shared-data
      mountPath: /etc/secrets

    - name: vault-token
      mountPath: /home/vault

    - name: config
      mountPath: /etc/consul-template

    env:
    - name: HOME
      value: /home/vault

    - name: VAULT_ADDR
      value: http://10.0.2.2:8200
    
    # Consul-Template looks in $HOME/.vault-token, $VAULT_TOKEN, or -vault-token (via CLI)
    args: ["-config=/etc/consul-template/consul-template-config.hcl", "-log-level=debug"]
  
  - name: app
    image: registry.hub.docker.com/sethvargo/vault-demo-app:0.1.0
    imagePullPolicy: Always

    volumeMounts:
    - name: shared-data
      mountPath: /etc/secrets

  - name: nginx-container
    image: nginx

    ports:
    - containerPort: 80

    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html